version: '3'
services:
  node:
    build: .
    container_name: "nodejs"    
    ports:      
      - 3000:3000
    volumes:
      - .:/api
    command: npm start
    restart: always    
    networks:
      lan:
networks:
  lan:
    name: infra_lan