POST http://localhost:3000/api/v1/proprietarios HTTP/1.1
content-type: application/json

{
	"nome": "Newton Gonzaga Costa",
	"rg":"20.498.544-4",
	"cpf": "099.103.097-42",
	"contatos": [
		{ "tipo": "celular", "valor":"(21) 98706-5099" },
		{ "tipo": "email", "valor":"ncosta.rj@gmail.com" }
	],
	"contas": [
		{
			"agencia":"0387",
			"numero":"15427-1",
			"banco": {
				"codigo":"341",
				"nome":"Itau Unibanco S/A"
			},
			"principal": true
		}
	]
}